---
- name: Install IBM Cloud Ansible Modules
  hosts: localhost
  vars:
    ibmcloud_provider_version: 1.1.0
    ansible_modules_base_url: http://ausgsa.ibm.com/~jwcarman/public/  # TODO: External URL

  tasks:
    - name: Create Ansible Plugins Directory
      file:
        path: $HOME/.ansible/plugins
        state: directory
        mode: '0755'

    - name: Download Ansible Modules
      get_url:
        url: "{{ ansible_modules_base_url }}/ibmcloud-ansible_v{{ ibmcloud_provider_version }}.zip"
        dest: /tmp/
      register: ibmcloud_ansible_zip

    - name: Unarchive IBM Cloud Ansible Modules
      unarchive:
        src: "{{ ibmcloud_ansible_zip.dest }}"
        dest: $HOME/.ansible/plugins
        remote_src: yes
