// Code generated by go-swagger; DO NOT EDIT.

package l_baas

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.ibm.com/Bluemix/riaas-go-client/riaas/models"
)

// NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams creates a new PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams object
// with the default values initialized.
func NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams() *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	var ()
	return &PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParamsWithTimeout creates a new PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParamsWithTimeout(timeout time.Duration) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	var ()
	return &PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams{

		timeout: timeout,
	}
}

// NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParamsWithContext creates a new PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParamsWithContext(ctx context.Context) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	var ()
	return &PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams{

		Context: ctx,
	}
}

// NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParamsWithHTTPClient creates a new PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParamsWithHTTPClient(client *http.Client) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	var ()
	return &PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams{
		HTTPClient: client,
	}
}

/*PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams contains all the parameters to send to the API endpoint
for the patch load balancers ID listeners listener ID policies policy ID rules rule ID operation typically these are written to a http.Request
*/
type PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams struct {

	/*Body
	  The rule template

	*/
	Body *models.ListenerPolicyRuleTemplatePatch
	/*Generation
	  The infrastructure generation for the request.

	*/
	Generation int64
	/*ID
	  The load balancer identifier

	*/
	ID string
	/*ListenerID
	  The listener identifier

	*/
	ListenerID string
	/*PolicyID
	  The policy identifier

	*/
	PolicyID string
	/*RuleID
	  The rule identifier

	*/
	RuleID string
	/*Version
	  Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current date may be provided. Specify the current date to request the latest version.

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithTimeout(timeout time.Duration) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithContext(ctx context.Context) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithHTTPClient(client *http.Client) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithBody(body *models.ListenerPolicyRuleTemplatePatch) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetBody(body *models.ListenerPolicyRuleTemplatePatch) {
	o.Body = body
}

// WithGeneration adds the generation to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithGeneration(generation int64) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetGeneration(generation)
	return o
}

// SetGeneration adds the generation to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetGeneration(generation int64) {
	o.Generation = generation
}

// WithID adds the id to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithID(id string) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetID(id string) {
	o.ID = id
}

// WithListenerID adds the listenerID to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithListenerID(listenerID string) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetListenerID(listenerID)
	return o
}

// SetListenerID adds the listenerId to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetListenerID(listenerID string) {
	o.ListenerID = listenerID
}

// WithPolicyID adds the policyID to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithPolicyID(policyID string) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetPolicyID(policyID)
	return o
}

// SetPolicyID adds the policyId to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetPolicyID(policyID string) {
	o.PolicyID = policyID
}

// WithRuleID adds the ruleID to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithRuleID(ruleID string) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetRuleID(ruleID)
	return o
}

// SetRuleID adds the ruleId to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetRuleID(ruleID string) {
	o.RuleID = ruleID
}

// WithVersion adds the version to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WithVersion(version string) *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the patch load balancers ID listeners listener ID policies policy ID rules rule ID params
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *PatchLoadBalancersIDListenersListenerIDPoliciesPolicyIDRulesRuleIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// query param generation
	qrGeneration := o.Generation
	qGeneration := swag.FormatInt64(qrGeneration)
	if qGeneration != "" {
		if err := r.SetQueryParam("generation", qGeneration); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param listener_id
	if err := r.SetPathParam("listener_id", o.ListenerID); err != nil {
		return err
	}

	// path param policy_id
	if err := r.SetPathParam("policy_id", o.PolicyID); err != nil {
		return err
	}

	// path param rule_id
	if err := r.SetPathParam("rule_id", o.RuleID); err != nil {
		return err
	}

	// query param version
	qrVersion := o.Version
	qVersion := qrVersion
	if qVersion != "" {
		if err := r.SetQueryParam("version", qVersion); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
