// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSharesShareIDTargetsIDParams creates a new GetSharesShareIDTargetsIDParams object
// with the default values initialized.
func NewGetSharesShareIDTargetsIDParams() *GetSharesShareIDTargetsIDParams {
	var ()
	return &GetSharesShareIDTargetsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSharesShareIDTargetsIDParamsWithTimeout creates a new GetSharesShareIDTargetsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSharesShareIDTargetsIDParamsWithTimeout(timeout time.Duration) *GetSharesShareIDTargetsIDParams {
	var ()
	return &GetSharesShareIDTargetsIDParams{

		timeout: timeout,
	}
}

// NewGetSharesShareIDTargetsIDParamsWithContext creates a new GetSharesShareIDTargetsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSharesShareIDTargetsIDParamsWithContext(ctx context.Context) *GetSharesShareIDTargetsIDParams {
	var ()
	return &GetSharesShareIDTargetsIDParams{

		Context: ctx,
	}
}

// NewGetSharesShareIDTargetsIDParamsWithHTTPClient creates a new GetSharesShareIDTargetsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSharesShareIDTargetsIDParamsWithHTTPClient(client *http.Client) *GetSharesShareIDTargetsIDParams {
	var ()
	return &GetSharesShareIDTargetsIDParams{
		HTTPClient: client,
	}
}

/*GetSharesShareIDTargetsIDParams contains all the parameters to send to the API endpoint
for the get shares share ID targets ID operation typically these are written to a http.Request
*/
type GetSharesShareIDTargetsIDParams struct {

	/*Generation
	  The infrastructure generation for the request.

	*/
	Generation int64
	/*ID
	  The mount target identifier

	*/
	ID string
	/*ShareID
	  The file share identifier

	*/
	ShareID string
	/*Version
	  Requests the version of the API as of a date in the format `YYYY-MM-DD`. Any date up to the current date may be provided. Specify the current date to request the latest version.

	*/
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) WithTimeout(timeout time.Duration) *GetSharesShareIDTargetsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) WithContext(ctx context.Context) *GetSharesShareIDTargetsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) WithHTTPClient(client *http.Client) *GetSharesShareIDTargetsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGeneration adds the generation to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) WithGeneration(generation int64) *GetSharesShareIDTargetsIDParams {
	o.SetGeneration(generation)
	return o
}

// SetGeneration adds the generation to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) SetGeneration(generation int64) {
	o.Generation = generation
}

// WithID adds the id to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) WithID(id string) *GetSharesShareIDTargetsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) SetID(id string) {
	o.ID = id
}

// WithShareID adds the shareID to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) WithShareID(shareID string) *GetSharesShareIDTargetsIDParams {
	o.SetShareID(shareID)
	return o
}

// SetShareID adds the shareId to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) SetShareID(shareID string) {
	o.ShareID = shareID
}

// WithVersion adds the version to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) WithVersion(version string) *GetSharesShareIDTargetsIDParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get shares share ID targets ID params
func (o *GetSharesShareIDTargetsIDParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetSharesShareIDTargetsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param generation
	qrGeneration := o.Generation
	qGeneration := swag.FormatInt64(qrGeneration)
	if qGeneration != "" {
		if err := r.SetQueryParam("generation", qGeneration); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param share_id
	if err := r.SetPathParam("share_id", o.ShareID); err != nil {
		return err
	}

	// query param version
	qrVersion := o.Version
	qVersion := qrVersion
	if qVersion != "" {
		if err := r.SetQueryParam("version", qVersion); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
