---
- name: POWER VSI Creation Demo
  hosts: localhost
  vars:
    pi_name: ansible-demo-power-vm
    sys_type: s922
    pi_image: "7200-03-03"
    proc_type: shared
    processors: "0.25"
    memory: "2"
    pi_cloud_instance_id: "YOUR PI CLOUD INSTANCE ID"
    ssh_public_key: "YOUR SSH PUBLIC KEY"
  tasks:
    - name: Check for existing SSH Key
      ibm_pi_key_info:
        pi_key_name: "{{ pi_name }}-ssh-key"
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
      failed_when:
        - pi_ssh_key_existing_output.rc != 0
        - '"does not exist" not in pi_ssh_key_existing_output.stderr'
      register: pi_ssh_key_existing_output

    - name: Save existing SSH Key as fact
      set_fact:
        cacheable: True
        pi_ssh_key: "{{ pi_ssh_key_existing_output.resource }}"
      when: pi_ssh_key_existing_output.resource.id is defined

    - name: Add new SSH Key
      ibm_pi_key:
        pi_key_name: "{{ pi_name }}-ssh-key"
        pi_ssh_key: "{{ ssh_public_key }}"
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
      register: pi_ssh_key_create_output
      when: pi_ssh_key_existing_output.resource.id is not defined

    - name: Save new SSH Key as fact
      set_fact:
        cacheable: True
        pi_ssh_key: "{{ pi_ssh_key_create_output.resource }}"
      when: pi_ssh_key_existing_output.resource.id is not defined

    - name: Retrieve image list
      ibm_pi_images_info:
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
      register: images_list

    - name: Set VM image name/id dictionary fact
      set_fact:
        image_dict: "{{ images_list.resource.image_info |
                        items2dict(key_name='image_name',
                        value_name='image_id') }}"

    - name: Check for existing Virtual Server Instance
      ibm_pi_instance_info:
        pi_instance_name: "{{ pi_name }}"
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
      failed_when:
        - pi_instance_existing_output.rc != 0
        - '"does not exist" not in pi_instance_existing_output.stderr'
      register: pi_instance_existing_output

    - name: Save existing Power VSI fact
      set_fact:
        cacheable: True
        pi_instance: "{{ pi_instance_existing_output.resource }}"
      when: pi_instance_existing_output.rc == 0

    - name: Create a POWER Virtual Server Instance
      ibm_pi_instance:
        state: available
        pi_memory: "{{ memory }}"
        pi_processors: "{{ processors }}"
        pi_instance_name: "{{ pi_name }}"
        pi_proc_type: "{{ proc_type }}"
        pi_migratable: True
        pi_image_id: "{{ image_dict[pi_image] }}"
        pi_volume_ids: []
        pi_network_ids: ['249859ed-2ff2-4534-8862-f2c2cc8eeda9']
        pi_public_network: True
        pi_key_pair_name: "{{ pi_ssh_key.pi_key_name }}"
        pi_sys_type: "{{ sys_type }}"
        pi_replication_policy: none
        pi_replication_scheme: suffix
        pi_replicants: "1"
        pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
        id: "{{ pi_instance.resource.id | default(omit) }}"
      register: pi_instance_create_output
      when: pi_instance_existing_output.rc != 0

    - name: Save new Power VSI fact
      set_fact:
        cacheable: True
        pi_instance: "{{ pi_instance_create_output.resource }}"
      when: pi_instance_create_output.resource is defined

    - name: Print Public IP Address
      debug:
        var: pi_instance.addresses[0].externalip

    - name: Add VSI to Ansible inventory
      add_host:
        name: "{{ pi_instance.addresses[0].externalip }}"
        ansible_user: root
        groups: new_vsi
        ansible_ssh_extra_args: -o StrictHostKeyChecking=no

- name: Connect to VSI
  hosts: new_vsi
  gather_facts: False
  tasks:
    - name: Wait for VSI to become reachable over SSH
      wait_for_connection:

    - name: Collect OS login message
      command: cat /etc/motd
      register: os_motd

    - name: Print MOTD
      debug:
        var: os_motd.stdout_lines
