// Code generated by go-swagger; DO NOT EDIT.

package compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.ibm.com/Bluemix/riaas-go-client/riaas/models"
)

// GetInstancesInstanceIDVolumeAttachmentsReader is a Reader for the GetInstancesInstanceIDVolumeAttachments structure.
type GetInstancesInstanceIDVolumeAttachmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInstancesInstanceIDVolumeAttachmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInstancesInstanceIDVolumeAttachmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetInstancesInstanceIDVolumeAttachmentsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInstancesInstanceIDVolumeAttachmentsOK creates a GetInstancesInstanceIDVolumeAttachmentsOK with default headers values
func NewGetInstancesInstanceIDVolumeAttachmentsOK() *GetInstancesInstanceIDVolumeAttachmentsOK {
	return &GetInstancesInstanceIDVolumeAttachmentsOK{}
}

/*GetInstancesInstanceIDVolumeAttachmentsOK handles this case with default header values.

dummy
*/
type GetInstancesInstanceIDVolumeAttachmentsOK struct {
	Payload *GetInstancesInstanceIDVolumeAttachmentsOKBody
}

func (o *GetInstancesInstanceIDVolumeAttachmentsOK) Error() string {
	return fmt.Sprintf("[GET /instances/{instance_id}/volume_attachments][%d] getInstancesInstanceIdVolumeAttachmentsOK  %+v", 200, o.Payload)
}

func (o *GetInstancesInstanceIDVolumeAttachmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetInstancesInstanceIDVolumeAttachmentsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInstancesInstanceIDVolumeAttachmentsNotFound creates a GetInstancesInstanceIDVolumeAttachmentsNotFound with default headers values
func NewGetInstancesInstanceIDVolumeAttachmentsNotFound() *GetInstancesInstanceIDVolumeAttachmentsNotFound {
	return &GetInstancesInstanceIDVolumeAttachmentsNotFound{}
}

/*GetInstancesInstanceIDVolumeAttachmentsNotFound handles this case with default header values.

error
*/
type GetInstancesInstanceIDVolumeAttachmentsNotFound struct {
	Payload *models.Riaaserror
}

func (o *GetInstancesInstanceIDVolumeAttachmentsNotFound) Error() string {
	return fmt.Sprintf("[GET /instances/{instance_id}/volume_attachments][%d] getInstancesInstanceIdVolumeAttachmentsNotFound  %+v", 404, o.Payload)
}

func (o *GetInstancesInstanceIDVolumeAttachmentsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetInstancesInstanceIDVolumeAttachmentsOKBody VolumeAttachmentCollection
swagger:model GetInstancesInstanceIDVolumeAttachmentsOKBody
*/
type GetInstancesInstanceIDVolumeAttachmentsOKBody struct {

	// Collection of volume attachments
	VolumeAttachments []*models.InstanceVolumeAttachment `json:"volume_attachments,omitempty"`
}

// Validate validates this get instances instance ID volume attachments o k body
func (o *GetInstancesInstanceIDVolumeAttachmentsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateVolumeAttachments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetInstancesInstanceIDVolumeAttachmentsOKBody) validateVolumeAttachments(formats strfmt.Registry) error {

	if swag.IsZero(o.VolumeAttachments) { // not required
		return nil
	}

	for i := 0; i < len(o.VolumeAttachments); i++ {
		if swag.IsZero(o.VolumeAttachments[i]) { // not required
			continue
		}

		if o.VolumeAttachments[i] != nil {
			if err := o.VolumeAttachments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getInstancesInstanceIdVolumeAttachmentsOK" + "." + "volume_attachments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetInstancesInstanceIDVolumeAttachmentsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetInstancesInstanceIDVolumeAttachmentsOKBody) UnmarshalBinary(b []byte) error {
	var res GetInstancesInstanceIDVolumeAttachmentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
