// Code generated by go-swagger; DO NOT EDIT.

package compute

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.ibm.com/Bluemix/riaas-go-client/riaas/models"
)

// PostInstancesReader is a Reader for the PostInstances structure.
type PostInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostInstancesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostInstancesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostInstancesCreated creates a PostInstancesCreated with default headers values
func NewPostInstancesCreated() *PostInstancesCreated {
	return &PostInstancesCreated{}
}

/*PostInstancesCreated handles this case with default header values.

dummy
*/
type PostInstancesCreated struct {
	Payload *models.Instance
}

func (o *PostInstancesCreated) Error() string {
	return fmt.Sprintf("[POST /instances][%d] postInstancesCreated  %+v", 201, o.Payload)
}

func (o *PostInstancesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Instance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostInstancesBadRequest creates a PostInstancesBadRequest with default headers values
func NewPostInstancesBadRequest() *PostInstancesBadRequest {
	return &PostInstancesBadRequest{}
}

/*PostInstancesBadRequest handles this case with default header values.

error
*/
type PostInstancesBadRequest struct {
	Payload *models.Riaaserror
}

func (o *PostInstancesBadRequest) Error() string {
	return fmt.Sprintf("[POST /instances][%d] postInstancesBadRequest  %+v", 400, o.Payload)
}

func (o *PostInstancesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
