// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PatchNetworkAclsNetworkACLIDRulesIDParamsBodyBefore patch network acls network Acl Id rules Id params body before
// swagger:model patchNetworkAclsNetworkAclIdRulesIdParamsBodyBefore
type PatchNetworkAclsNetworkACLIDRulesIDParamsBodyBefore struct {

	// The unique identifier for this rule
	// Pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
	ID string `json:"id,omitempty"`
}

// Validate validates this patch network acls network Acl Id rules Id params body before
func (m *PatchNetworkAclsNetworkACLIDRulesIDParamsBodyBefore) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PatchNetworkAclsNetworkACLIDRulesIDParamsBodyBefore) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.Pattern("id", "body", string(m.ID), `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PatchNetworkAclsNetworkACLIDRulesIDParamsBodyBefore) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchNetworkAclsNetworkACLIDRulesIDParamsBodyBefore) UnmarshalBinary(b []byte) error {
	var res PatchNetworkAclsNetworkACLIDRulesIDParamsBodyBefore
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
