// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems FloatingIPTemplateBasic
// swagger:model postInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems
type PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems struct {

	// The globally unique IP address
	Address string `json:"address,omitempty"`

	// The CRN for this floating IP
	Crn string `json:"crn,omitempty"`

	// The user-defined name for this floating IP
	// Pattern: ^[A-Za-z][-A-Za-z0-9_]*$
	Name string `json:"name,omitempty"`

	// resource group
	ResourceGroup *PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItemsResourceGroup `json:"resource_group,omitempty"`
}

// Validate validates this post instances params body primary network interface floating ips items
func (m *PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourceGroup(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", string(m.Name), `^[A-Za-z][-A-Za-z0-9_]*$`); err != nil {
		return err
	}

	return nil
}

func (m *PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems) validateResourceGroup(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourceGroup) { // not required
		return nil
	}

	if m.ResourceGroup != nil {
		if err := m.ResourceGroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resource_group")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems) UnmarshalBinary(b []byte) error {
	var res PostInstancesParamsBodyPrimaryNetworkInterfaceFloatingIpsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
