apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-config
  labels:
    app: pvc-test
spec:
  selector:
    matchLabels:
      app: pvc-test
  template:
    metadata:
      labels:
        app: pvc-test
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        name: pvc-test
        volumeMounts:
        - name: pvc-test-v
          mountPath: /tmp/test
      volumes:
      - name: pvc-test-v
        persistentVolumeClaim:
          claimName: CLAIM_NAME
