// Copyright IBM Corp. 2022 All Rights Reserved.
// Licensed under the Mozilla Public License v2.0

package transitgateway

const (
	tgConnName                                = "name"
	tgConnections                             = "connections"
	ID                                        = "id"
	tgBaseNetworkType                         = "base_network_type"
	tgLocalConnectionLocations                = "local_connection_locations"
	tgLocationsDisplayName                    = "display_name"
	tgLocations                               = "locations"
	tgLocationsName                           = "name"
	tgLocationsBillingLoc                     = "billing_location"
	tgLocationsType                           = "type"
	tgRouteReport                             = "route_report"
	tgRouteReports                            = "route_reports"
	tgRouteReportConnections                  = "connections"
	tgRouteReportOverlappingRoutes            = "overlapping_routes"
	tgRouteReportOverlappingRoutesDetail      = "routes"
	tgRouteReportConnectionBgps               = "bgps"
	tgRouteReportConnectionBgpAsPath          = "as_path"
	tgRouteReportConnectionBgpIsUsed          = "is_used"
	tgRouteReportConnectionBgpLocalPreference = "local_preference"
	tgRouteReportConnectionBgpPrefix          = "prefix"
	tgRouteReportConnectionRoutes             = "routes"
	tgRouteReportConnectionRoutePrefix        = "prefix"
	tgRouteReportConnectionType               = "type"
	tgRouteReportOverlappingPrefix            = "prefix"
	tgXacGatewayId                            = "gateway"
	tgXacConnectionId                         = "connection_id"
	tgConnectionAction                        = "action"
	isTransitGatewayConnectionTunnelDeleting  = "deleting"
	isTransitGatewayConnectionTunnelDetaching = "detaching"
	isTransitGatewayConnectionTunnelDeleted   = "detached"
	isTransitGatewayConnectionTunnelPending   = "pending"
	isTransitGatewayConnectionTunnelAttached  = "attached"
	tgGatewayConnections                      = "gateway_connections"
	tgNetworkId                               = "network_id"
	tgNetworkType                             = "network_type"
	tgNetworkAccountID                        = "network_account_id"
	tgConectionCreatedAt                      = "created_at"
	tgConnectionStatus                        = "status"
	tgGatewayId                               = "gateway"
	isTransitGatewayConnectionDeleting        = "deleting"
	isTransitGatewayConnectionDetaching       = "detaching"
	isTransitGatewayConnectionDeleted         = "detached"
	isTransitGatewayConnectionPending         = "pending"
	isTransitGatewayConnectionAttached        = "attached"
	tgRequestStatus                           = "request_status"
	tgConnectionId                            = "connection_id"
	tgBaseConnectionId                        = "base_connection_id"
	tgLocalBgpAsn                             = "local_bgp_asn"
	tgLocalGatewayIp                          = "local_gateway_ip"
	tgLocalTunnelIp                           = "local_tunnel_ip"
	tgRemoteBgpAsn                            = "remote_bgp_asn"
	tgRemoteGatewayIp                         = "remote_gateway_ip"
	tgRemoteTunnelIp                          = "remote_tunnel_ip"
	tgZone                                    = "zone"
	tgMtu                                     = "mtu"
	tgrGREtunnels                             = "tunnels"
	tgGreTunnelId                             = "tunnel_id"
	tgGreTunnelStatus                         = "status"
	tgconTunnelName                           = "name"
	tgRouteReportId                           = "route_report_id"
	isTransitGatewayRouteReportPending        = "pending"
	isTransitGatewayRouteReportDone           = "complete"
	tgGateways                                = "transit_gateways"
	tgResourceGroup                           = "resource_group"
	tgID                                      = "id"
	tgCrn                                     = "crn"
	tgName                                    = "name"
	tgLocation                                = "location"
	tgCreatedAt                               = "created_at"
	tgGlobal                                  = "global"
	tgStatus                                  = "status"
	tgUpdatedAt                               = "updated_at"
	tgGatewayTags                             = "tags"
	isTransitGatewayProvisioning              = "provisioning"
	isTransitGatewayProvisioningDone          = "done"
	isTransitGatewayDeleting                  = "deleting"
	isTransitGatewayDeleted                   = "done"
	tgPrefixFilters                           = "prefix_filters"
	tgAction                                  = "action"
	tgBefore                                  = "before"
	tgGe                                      = "ge"
	tgLe                                      = "le"
	tgPrefix                                  = "prefix"
	tgPrefixFilterId                          = "filter_id"
	tgDefaultPrefixFilter                     = "default_prefix_filter"
)

func NewInt64Pointer(v int64) *int64 {
	return &v
}

func NewStrPointer(v string) *string {
	return &v
}
