// Copyright IBM Corp. 2026 All Rights Reserved.
// Licensed under the Mozilla Public License v2.0

package transitgateway_test

import (
	"fmt"
	"os"
	"strings"
	"testing"

	acc "github.com/IBM-Cloud/terraform-provider-ibm/ibm/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

const (
	drsGatewayIDEnv = "IBM_TG_DRS_GATEWAY_ID"
	drsCRNEnv       = "IBM_TG_DRS_CRN"
	drsCIDREnv      = "IBM_TG_DRS_CIDR"
)

// TestAccIBMTransitGatewayConnectionDynamicRouteServer_basic requires a DRS
// whose VPC underlay is already connected to the gateway supplied by the test
// environment. The test owns and removes only the DRS connection.
func TestAccIBMTransitGatewayConnectionDynamicRouteServer_basic(t *testing.T) {
	gatewayID := testAccDynamicRouteServerEnv(t, drsGatewayIDEnv)
	drsCRN := testAccDynamicRouteServerEnv(t, drsCRNEnv)
	cidr := testAccDynamicRouteServerEnv(t, drsCIDREnv)
	connectionName := fmt.Sprintf("tg-connection-drs-%d", acctest.RandIntRange(10, 100))
	resourceName := "ibm_tg_connection.test_tg_drs_connection"

	resource.Test(t, resource.TestCase{
		PreCheck:     func() { acc.TestAccPreCheck(t) },
		Providers:    acc.TestAccProviders,
		CheckDestroy: testAccCheckIBMTransitGatewayConnectionDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccCheckIBMTransitGatewayDynamicRouteServerConnectionConfig(
					gatewayID,
					connectionName,
					drsCRN,
					cidr,
				),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckIBMTransitGatewayConnectionExists(resourceName, ""),
					resource.TestCheckResourceAttr(resourceName, "name", connectionName),
					resource.TestCheckResourceAttr(resourceName, "gateway", gatewayID),
					resource.TestCheckResourceAttr(resourceName, "network_type", "dynamic_route_server"),
					resource.TestCheckResourceAttr(resourceName, "network_id", drsCRN),
					resource.TestCheckResourceAttr(resourceName, "cidr", cidr),
					resource.TestCheckResourceAttr(resourceName, "status", "attached"),
					resource.TestCheckResourceAttrSet(resourceName, "connection_id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccDynamicRouteServerEnv(t *testing.T, name string) string {
	t.Helper()

	value := strings.TrimSpace(os.Getenv(name))
	if value == "" {
		t.Skipf("Skipping DRS acceptance test because %s is not set", name)
	}
	return value
}

func testAccCheckIBMTransitGatewayDynamicRouteServerConnectionConfig(gatewayID, connectionName, drsCRN, cidr string) string {
	return fmt.Sprintf(`
resource "ibm_tg_connection" "test_tg_drs_connection" {
	gateway      = %q
	name         = %q
	network_type = "dynamic_route_server"
	network_id   = %q
	cidr         = %q

	lifecycle {
		# DRS tunnels are generated by the service. The tunnels block is an
		# input for redundant_gre connections and is not configured for DRS.
		ignore_changes = [tunnels]
	}
}
`, gatewayID, connectionName, drsCRN, cidr)
}
