blank_issues_enabled: false
contact_links:
  - name: Terraform Core Bug Reports and Feature Requests
    url: https://github.com/hashicorp/terraform/issues/new/choose
    about: Terraform Core, which handles the Terraform configuration language, CLI commands, and resource dependency graph, has its own codebase. Bug reports and feature requests for those pieces of functionality should be directed to that repository.
  - name: Terraform Language or Workflow Questions
    url: https://discuss.hashicorp.com/c/terraform-core
    about: Please ask and answer language or workflow related questions through the Terraform Core Community Forum.

