# roles/mariadb/tasks/install.yml
---

- name: Add official MariaDB repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB repository
    baseurl: "http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower|regex_replace('redhat', 'rhel') }}{{ ansible_distribution_major_version }}-amd64"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
  tags: mariadb

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
