// Code generated by go-swagger; DO NOT EDIT.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.ibm.com/Bluemix/riaas-go-client/riaas/models"
)

// DeleteSecurityGroupsSecurityGroupIDRulesIDReader is a Reader for the DeleteSecurityGroupsSecurityGroupIDRulesID structure.
type DeleteSecurityGroupsSecurityGroupIDRulesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSecurityGroupsSecurityGroupIDRulesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteSecurityGroupsSecurityGroupIDRulesIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteSecurityGroupsSecurityGroupIDRulesIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSecurityGroupsSecurityGroupIDRulesIDNoContent creates a DeleteSecurityGroupsSecurityGroupIDRulesIDNoContent with default headers values
func NewDeleteSecurityGroupsSecurityGroupIDRulesIDNoContent() *DeleteSecurityGroupsSecurityGroupIDRulesIDNoContent {
	return &DeleteSecurityGroupsSecurityGroupIDRulesIDNoContent{}
}

/*DeleteSecurityGroupsSecurityGroupIDRulesIDNoContent handles this case with default header values.

error
*/
type DeleteSecurityGroupsSecurityGroupIDRulesIDNoContent struct {
	Payload *models.Riaaserror
}

func (o *DeleteSecurityGroupsSecurityGroupIDRulesIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /security_groups/{security_group_id}/rules/{id}][%d] deleteSecurityGroupsSecurityGroupIdRulesIdNoContent  %+v", 204, o.Payload)
}

func (o *DeleteSecurityGroupsSecurityGroupIDRulesIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecurityGroupsSecurityGroupIDRulesIDNotFound creates a DeleteSecurityGroupsSecurityGroupIDRulesIDNotFound with default headers values
func NewDeleteSecurityGroupsSecurityGroupIDRulesIDNotFound() *DeleteSecurityGroupsSecurityGroupIDRulesIDNotFound {
	return &DeleteSecurityGroupsSecurityGroupIDRulesIDNotFound{}
}

/*DeleteSecurityGroupsSecurityGroupIDRulesIDNotFound handles this case with default header values.

error
*/
type DeleteSecurityGroupsSecurityGroupIDRulesIDNotFound struct {
	Payload *models.Riaaserror
}

func (o *DeleteSecurityGroupsSecurityGroupIDRulesIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /security_groups/{security_group_id}/rules/{id}][%d] deleteSecurityGroupsSecurityGroupIdRulesIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteSecurityGroupsSecurityGroupIDRulesIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError creates a DeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError with default headers values
func NewDeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError() *DeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError {
	return &DeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError{}
}

/*DeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError handles this case with default header values.

error
*/
type DeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError struct {
	Payload *models.Riaaserror
}

func (o *DeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /security_groups/{security_group_id}/rules/{id}][%d] deleteSecurityGroupsSecurityGroupIdRulesIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSecurityGroupsSecurityGroupIDRulesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
