// Code generated by go-swagger; DO NOT EDIT.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.ibm.com/Bluemix/riaas-go-client/riaas/models"
)

// GetSubnetsIDReader is a Reader for the GetSubnetsID structure.
type GetSubnetsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubnetsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSubnetsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetSubnetsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetSubnetsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSubnetsIDOK creates a GetSubnetsIDOK with default headers values
func NewGetSubnetsIDOK() *GetSubnetsIDOK {
	return &GetSubnetsIDOK{}
}

/*GetSubnetsIDOK handles this case with default header values.

dummy
*/
type GetSubnetsIDOK struct {
	Payload *models.Subnet
}

func (o *GetSubnetsIDOK) Error() string {
	return fmt.Sprintf("[GET /subnets/{id}][%d] getSubnetsIdOK  %+v", 200, o.Payload)
}

func (o *GetSubnetsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Subnet)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSubnetsIDNotFound creates a GetSubnetsIDNotFound with default headers values
func NewGetSubnetsIDNotFound() *GetSubnetsIDNotFound {
	return &GetSubnetsIDNotFound{}
}

/*GetSubnetsIDNotFound handles this case with default header values.

error
*/
type GetSubnetsIDNotFound struct {
	Payload *models.Riaaserror
}

func (o *GetSubnetsIDNotFound) Error() string {
	return fmt.Sprintf("[GET /subnets/{id}][%d] getSubnetsIdNotFound  %+v", 404, o.Payload)
}

func (o *GetSubnetsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSubnetsIDInternalServerError creates a GetSubnetsIDInternalServerError with default headers values
func NewGetSubnetsIDInternalServerError() *GetSubnetsIDInternalServerError {
	return &GetSubnetsIDInternalServerError{}
}

/*GetSubnetsIDInternalServerError handles this case with default header values.

error
*/
type GetSubnetsIDInternalServerError struct {
	Payload *models.Riaaserror
}

func (o *GetSubnetsIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /subnets/{id}][%d] getSubnetsIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSubnetsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
