// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetInstancesInstanceIDVolumeAttachmentsOKBody VolumeAttachmentCollection
// swagger:model getInstancesInstanceIdVolumeAttachmentsOKBody
type GetInstancesInstanceIDVolumeAttachmentsOKBody struct {

	// Collection of volume attachments
	VolumeAttachments []*InstanceVolumeAttachment `json:"volume_attachments,omitempty"`
}

// Validate validates this get instances instance Id volume attachments o k body
func (m *GetInstancesInstanceIDVolumeAttachmentsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVolumeAttachments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetInstancesInstanceIDVolumeAttachmentsOKBody) validateVolumeAttachments(formats strfmt.Registry) error {

	if swag.IsZero(m.VolumeAttachments) { // not required
		return nil
	}

	for i := 0; i < len(m.VolumeAttachments); i++ {
		if swag.IsZero(m.VolumeAttachments[i]) { // not required
			continue
		}

		if m.VolumeAttachments[i] != nil {
			if err := m.VolumeAttachments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("volume_attachments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetInstancesInstanceIDVolumeAttachmentsOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetInstancesInstanceIDVolumeAttachmentsOKBody) UnmarshalBinary(b []byte) error {
	var res GetInstancesInstanceIDVolumeAttachmentsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
