// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Pool Pool
// swagger:model Pool
type Pool struct {

	// The load balancing algorithm.
	// Enum: [round_robin weighted_round_robin least_connections]
	Algorithm string `json:"algorithm,omitempty"`

	// The date and time that this pool was created
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The health monitor of this pool.
	HealthMonitor *HealthMonitorTemplate `json:"health_monitor,omitempty"`

	// The pool's canonical URL..
	// Pattern: ^http(s)?:\/\/([^\/?#]*)([^?#]*)(\?([^#]*))?(#(.*))?$
	Href string `json:"href,omitempty"`

	// The pool's unique identifier.
	// Format: uuid
	ID strfmt.UUID `json:"id,omitempty"`

	// The backend server members of the pool
	Members []*MemberReference `json:"members"`

	// The name of the pool.
	// Pattern: ^[A-Za-z][-A-Za-z0-9_]*$
	Name string `json:"name,omitempty"`

	// The pool protocol.
	// Enum: [http tcp]
	Protocol string `json:"protocol,omitempty"`

	// The provisioning status of this pool
	// Enum: [active create_pending update_pending delete_pending maintenance_pending]
	ProvisioningStatus string `json:"provisioning_status,omitempty"`

	// The session persistence of this pool.
	SessionPersistence *SessionPersistenceTemplate `json:"session_persistence,omitempty"`
}

// Validate validates this pool
func (m *Pool) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHealthMonitor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHref(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMembers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvisioningStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionPersistence(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var poolTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["round_robin","weighted_round_robin","least_connections"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		poolTypeAlgorithmPropEnum = append(poolTypeAlgorithmPropEnum, v)
	}
}

const (

	// PoolAlgorithmRoundRobin captures enum value "round_robin"
	PoolAlgorithmRoundRobin string = "round_robin"

	// PoolAlgorithmWeightedRoundRobin captures enum value "weighted_round_robin"
	PoolAlgorithmWeightedRoundRobin string = "weighted_round_robin"

	// PoolAlgorithmLeastConnections captures enum value "least_connections"
	PoolAlgorithmLeastConnections string = "least_connections"
)

// prop value enum
func (m *Pool) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, poolTypeAlgorithmPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Pool) validateAlgorithm(formats strfmt.Registry) error {

	if swag.IsZero(m.Algorithm) { // not required
		return nil
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	return nil
}

func (m *Pool) validateCreatedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Pool) validateHealthMonitor(formats strfmt.Registry) error {

	if swag.IsZero(m.HealthMonitor) { // not required
		return nil
	}

	if m.HealthMonitor != nil {
		if err := m.HealthMonitor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("health_monitor")
			}
			return err
		}
	}

	return nil
}

func (m *Pool) validateHref(formats strfmt.Registry) error {

	if swag.IsZero(m.Href) { // not required
		return nil
	}

	if err := validate.Pattern("href", "body", string(m.Href), `^http(s)?:\/\/([^\/?#]*)([^?#]*)(\?([^#]*))?(#(.*))?$`); err != nil {
		return err
	}

	return nil
}

func (m *Pool) validateID(formats strfmt.Registry) error {

	if swag.IsZero(m.ID) { // not required
		return nil
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Pool) validateMembers(formats strfmt.Registry) error {

	if swag.IsZero(m.Members) { // not required
		return nil
	}

	for i := 0; i < len(m.Members); i++ {
		if swag.IsZero(m.Members[i]) { // not required
			continue
		}

		if m.Members[i] != nil {
			if err := m.Members[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("members" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Pool) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", string(m.Name), `^[A-Za-z][-A-Za-z0-9_]*$`); err != nil {
		return err
	}

	return nil
}

var poolTypeProtocolPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["http","tcp"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		poolTypeProtocolPropEnum = append(poolTypeProtocolPropEnum, v)
	}
}

const (

	// PoolProtocolHTTP captures enum value "http"
	PoolProtocolHTTP string = "http"

	// PoolProtocolTCP captures enum value "tcp"
	PoolProtocolTCP string = "tcp"
)

// prop value enum
func (m *Pool) validateProtocolEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, poolTypeProtocolPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Pool) validateProtocol(formats strfmt.Registry) error {

	if swag.IsZero(m.Protocol) { // not required
		return nil
	}

	// value enum
	if err := m.validateProtocolEnum("protocol", "body", m.Protocol); err != nil {
		return err
	}

	return nil
}

var poolTypeProvisioningStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["active","create_pending","update_pending","delete_pending","maintenance_pending"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		poolTypeProvisioningStatusPropEnum = append(poolTypeProvisioningStatusPropEnum, v)
	}
}

const (

	// PoolProvisioningStatusActive captures enum value "active"
	PoolProvisioningStatusActive string = "active"

	// PoolProvisioningStatusCreatePending captures enum value "create_pending"
	PoolProvisioningStatusCreatePending string = "create_pending"

	// PoolProvisioningStatusUpdatePending captures enum value "update_pending"
	PoolProvisioningStatusUpdatePending string = "update_pending"

	// PoolProvisioningStatusDeletePending captures enum value "delete_pending"
	PoolProvisioningStatusDeletePending string = "delete_pending"

	// PoolProvisioningStatusMaintenancePending captures enum value "maintenance_pending"
	PoolProvisioningStatusMaintenancePending string = "maintenance_pending"
)

// prop value enum
func (m *Pool) validateProvisioningStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, poolTypeProvisioningStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Pool) validateProvisioningStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.ProvisioningStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateProvisioningStatusEnum("provisioning_status", "body", m.ProvisioningStatus); err != nil {
		return err
	}

	return nil
}

func (m *Pool) validateSessionPersistence(formats strfmt.Registry) error {

	if swag.IsZero(m.SessionPersistence) { // not required
		return nil
	}

	if m.SessionPersistence != nil {
		if err := m.SessionPersistence.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("session_persistence")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Pool) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pool) UnmarshalBinary(b []byte) error {
	var res Pool
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
