// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PoolTemplatePatch pool template patch
// swagger:model PoolTemplatePatch
type PoolTemplatePatch struct {

	// The load balancing algorithm.
	// Enum: [round_robin weighted_round_robin least_connections]
	Algorithm string `json:"algorithm,omitempty"`

	// The health monitor of this pool.
	HealthMonitor *HealthMonitorTemplate `json:"health_monitor,omitempty"`

	// The name of the pool.
	// Pattern: ^[A-Za-z][-A-Za-z0-9_]*$
	Name string `json:"name,omitempty"`

	// The pool protocol.
	// Enum: [http tcp]
	Protocol string `json:"protocol,omitempty"`

	// The session persistence of this pool.
	SessionPersistence *SessionPersistenceTemplate `json:"session_persistence,omitempty"`
}

// Validate validates this pool template patch
func (m *PoolTemplatePatch) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHealthMonitor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProtocol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionPersistence(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var poolTemplatePatchTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["round_robin","weighted_round_robin","least_connections"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		poolTemplatePatchTypeAlgorithmPropEnum = append(poolTemplatePatchTypeAlgorithmPropEnum, v)
	}
}

const (

	// PoolTemplatePatchAlgorithmRoundRobin captures enum value "round_robin"
	PoolTemplatePatchAlgorithmRoundRobin string = "round_robin"

	// PoolTemplatePatchAlgorithmWeightedRoundRobin captures enum value "weighted_round_robin"
	PoolTemplatePatchAlgorithmWeightedRoundRobin string = "weighted_round_robin"

	// PoolTemplatePatchAlgorithmLeastConnections captures enum value "least_connections"
	PoolTemplatePatchAlgorithmLeastConnections string = "least_connections"
)

// prop value enum
func (m *PoolTemplatePatch) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, poolTemplatePatchTypeAlgorithmPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PoolTemplatePatch) validateAlgorithm(formats strfmt.Registry) error {

	if swag.IsZero(m.Algorithm) { // not required
		return nil
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	return nil
}

func (m *PoolTemplatePatch) validateHealthMonitor(formats strfmt.Registry) error {

	if swag.IsZero(m.HealthMonitor) { // not required
		return nil
	}

	if m.HealthMonitor != nil {
		if err := m.HealthMonitor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("health_monitor")
			}
			return err
		}
	}

	return nil
}

func (m *PoolTemplatePatch) validateName(formats strfmt.Registry) error {

	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.Pattern("name", "body", string(m.Name), `^[A-Za-z][-A-Za-z0-9_]*$`); err != nil {
		return err
	}

	return nil
}

var poolTemplatePatchTypeProtocolPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["http","tcp"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		poolTemplatePatchTypeProtocolPropEnum = append(poolTemplatePatchTypeProtocolPropEnum, v)
	}
}

const (

	// PoolTemplatePatchProtocolHTTP captures enum value "http"
	PoolTemplatePatchProtocolHTTP string = "http"

	// PoolTemplatePatchProtocolTCP captures enum value "tcp"
	PoolTemplatePatchProtocolTCP string = "tcp"
)

// prop value enum
func (m *PoolTemplatePatch) validateProtocolEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, poolTemplatePatchTypeProtocolPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PoolTemplatePatch) validateProtocol(formats strfmt.Registry) error {

	if swag.IsZero(m.Protocol) { // not required
		return nil
	}

	// value enum
	if err := m.validateProtocolEnum("protocol", "body", m.Protocol); err != nil {
		return err
	}

	return nil
}

func (m *PoolTemplatePatch) validateSessionPersistence(formats strfmt.Registry) error {

	if swag.IsZero(m.SessionPersistence) { // not required
		return nil
	}

	if m.SessionPersistence != nil {
		if err := m.SessionPersistence.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("session_persistence")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PoolTemplatePatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoolTemplatePatch) UnmarshalBinary(b []byte) error {
	var res PoolTemplatePatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
