// Code generated by go-swagger; DO NOT EDIT.

package geography

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.ibm.com/Bluemix/riaas-go-client/riaas/models"
)

// GetRegionsRegionNameZonesReader is a Reader for the GetRegionsRegionNameZones structure.
type GetRegionsRegionNameZonesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRegionsRegionNameZonesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRegionsRegionNameZonesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetRegionsRegionNameZonesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetRegionsRegionNameZonesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRegionsRegionNameZonesOK creates a GetRegionsRegionNameZonesOK with default headers values
func NewGetRegionsRegionNameZonesOK() *GetRegionsRegionNameZonesOK {
	return &GetRegionsRegionNameZonesOK{}
}

/*GetRegionsRegionNameZonesOK handles this case with default header values.

dummy
*/
type GetRegionsRegionNameZonesOK struct {
	Payload *GetRegionsRegionNameZonesOKBody
}

func (o *GetRegionsRegionNameZonesOK) Error() string {
	return fmt.Sprintf("[GET /regions/{region_name}/zones][%d] getRegionsRegionNameZonesOK  %+v", 200, o.Payload)
}

func (o *GetRegionsRegionNameZonesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetRegionsRegionNameZonesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegionsRegionNameZonesNotFound creates a GetRegionsRegionNameZonesNotFound with default headers values
func NewGetRegionsRegionNameZonesNotFound() *GetRegionsRegionNameZonesNotFound {
	return &GetRegionsRegionNameZonesNotFound{}
}

/*GetRegionsRegionNameZonesNotFound handles this case with default header values.

error
*/
type GetRegionsRegionNameZonesNotFound struct {
	Payload *models.Riaaserror
}

func (o *GetRegionsRegionNameZonesNotFound) Error() string {
	return fmt.Sprintf("[GET /regions/{region_name}/zones][%d] getRegionsRegionNameZonesNotFound  %+v", 404, o.Payload)
}

func (o *GetRegionsRegionNameZonesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRegionsRegionNameZonesInternalServerError creates a GetRegionsRegionNameZonesInternalServerError with default headers values
func NewGetRegionsRegionNameZonesInternalServerError() *GetRegionsRegionNameZonesInternalServerError {
	return &GetRegionsRegionNameZonesInternalServerError{}
}

/*GetRegionsRegionNameZonesInternalServerError handles this case with default header values.

error
*/
type GetRegionsRegionNameZonesInternalServerError struct {
	Payload *models.Riaaserror
}

func (o *GetRegionsRegionNameZonesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /regions/{region_name}/zones][%d] getRegionsRegionNameZonesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetRegionsRegionNameZonesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Riaaserror)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetRegionsRegionNameZonesOKBody ZoneCollection
swagger:model GetRegionsRegionNameZonesOKBody
*/
type GetRegionsRegionNameZonesOKBody struct {

	// Collection of zones
	// Required: true
	Zones []*models.Zone `json:"zones"`
}

// Validate validates this get regions region name zones o k body
func (o *GetRegionsRegionNameZonesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateZones(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRegionsRegionNameZonesOKBody) validateZones(formats strfmt.Registry) error {

	if err := validate.Required("getRegionsRegionNameZonesOK"+"."+"zones", "body", o.Zones); err != nil {
		return err
	}

	for i := 0; i < len(o.Zones); i++ {
		if swag.IsZero(o.Zones[i]) { // not required
			continue
		}

		if o.Zones[i] != nil {
			if err := o.Zones[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getRegionsRegionNameZonesOK" + "." + "zones" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetRegionsRegionNameZonesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetRegionsRegionNameZonesOKBody) UnmarshalBinary(b []byte) error {
	var res GetRegionsRegionNameZonesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
