package power

import "time"

const (
	// Arguments
	Arg_CloudConnectionName                 = "pi_cloud_connection_name"
	Arg_CloudInstanceID                     = "pi_cloud_instance_id"
	Arg_ImageName                           = "pi_image_name"
	Arg_InstanceName                        = "pi_instance_name"
	Arg_Key                                 = "pi_ssh_key"
	Arg_KeyName                             = "pi_key_name"
	Arg_NetworkName                         = "pi_network_name"
	Arg_PlacementGroupName                  = "pi_placement_group_name"
	Arg_SAP                                 = "sap"
	Arg_SAPProfileID                        = "pi_sap_profile_id"
	Arg_SPPPlacementGroupID                 = "pi_spp_placement_group_id"
	Arg_SPPPlacementGroupName               = "pi_spp_placement_group_name"
	Arg_SPPPlacementGroupPolicy             = "pi_spp_placement_group_policy"
	Arg_SharedProcessorPoolHostGroup        = "pi_shared_processor_pool_host_group"
	Arg_SharedProcessorPoolID               = "pi_shared_processor_pool_id"
	Arg_SharedProcessorPoolName             = "pi_shared_processor_pool_name"
	Arg_SharedProcessorPoolPlacementGroupID = "pi_shared_processor_pool_placement_group_id"
	Arg_SharedProcessorPoolReservedCores    = "pi_shared_processor_pool_reserved_cores"
	Arg_StoragePool                         = "pi_storage_pool"
	Arg_StorageType                         = "pi_storage_type"
	Arg_VTL                                 = "vtl"
	Arg_VolumeGroupID                       = "pi_volume_group_id"
	Arg_VolumeID                            = "pi_volume_id"
	Arg_VolumeOnboardingID                  = "pi_volume_onboarding_id"

	// Attributes
	Attr_AccessConfig                                = "access_config"
	Attr_Action                                      = "action"
	Attr_Addresses                                   = "addresses"
	Attr_AllocatedCores                              = "allocated_cores"
	Attr_Architecture                                = "architecture"
	Attr_Auxiliary                                   = "auxiliary"
	Attr_AuxiliaryChangedVolumeName                  = "auxiliary_changed_volume_name"
	Attr_AuxiliaryVolumeName                         = "auxiliary_volume_name"
	Attr_AvailabilityZone                            = "availability_zone"
	Attr_AvailableCores                              = "available_cores"
	Attr_AvailableIPCount                            = "available_ip_count"
	Attr_BootVolumeID                                = "boot_volume_id"
	Attr_Bootable                                    = "bootable"
	Attr_CIDR                                        = "cidr"
	Attr_CPUs                                        = "cpus"
	Attr_CRN                                         = "crn"
	Attr_Capabilities                                = "capabilities"
	Attr_Capacity                                    = "capacity"
	Attr_Certified                                   = "certified"
	Attr_ClassicEnabled                              = "classic_enabled"
	Attr_CloudConnectionID                           = "cloud_connection_id"
	Attr_CloudInstanceID                             = "cloud_instance_id"
	Attr_CloudInstances                              = "cloud_instances"
	Attr_Code                                        = "code"
	Attr_ConnectionMode                              = "connection_mode"
	Attr_Connections                                 = "connections"
	Attr_ConsistencyGroupName                        = "consistency_group_name"
	Attr_ConsoleLanguages                            = "console_languages"
	Attr_ContainerFormat                             = "container_format"
	Attr_CopyRate                                    = "copy_rate"
	Attr_CopyType                                    = "copy_type"
	Attr_CoreMemoryRatio                             = "core_memory_ratio"
	Attr_Cores                                       = "cores"
	Attr_CreateTime                                  = "create_time"
	Attr_CreationDate                                = "creation_date"
	Attr_CyclePeriodSeconds                          = "cycle_period_seconds"
	Attr_CyclingMode                                 = "cycling_mode"
	Attr_DNS                                         = "dns"
	Attr_Datacenters                                 = "datacenters"
	Attr_Default                                     = "default"
	Attr_DeploymentType                              = "deployment_type"
	Attr_Description                                 = "description"
	Attr_DisasterRecoveryLocations                   = "disaster_recovery_locations"
	Attr_DiskFormat                                  = "disk_format"
	Attr_DiskType                                    = "disk_type"
	Attr_Enabled                                     = "enabled"
	Attr_Endianness                                  = "endianness"
	Attr_ExternalIP                                  = "external_ip"
	Attr_FailureMessage                              = "failure_message"
	Attr_FlashCopyMappings                           = "flash_copy_mappings"
	Attr_FlashCopyName                               = "flash_copy_name"
	Attr_FreezeTime                                  = "freeze_time"
	Attr_Gateway                                     = "gateway"
	Attr_GlobalRouting                               = "global_routing"
	Attr_GreDestinationAddress                       = "gre_destination_address"
	Attr_GreSourceAddress                            = "gre_source_address"
	Attr_GroupID                                     = "group_id"
	Attr_HealthStatus                                = "health_status"
	Attr_HostID                                      = "host_id"
	Attr_Href                                        = "href"
	Attr_Hypervisor                                  = "hypervisor"
	Attr_HypervisorType                              = "hypervisor_type"
	Attr_IBMIPAddress                                = "ibm_ip_address"
	Attr_ID                                          = "id"
	Attr_IP                                          = "ip"
	Attr_IPAddress                                   = "ipaddress"
	Attr_IPOctet                                     = "ipoctet"
	Attr_ImageID                                     = "image_id"
	Attr_ImageInfo                                   = "image_info"
	Attr_ImageType                                   = "image_type"
	Attr_Images                                      = "images"
	Attr_InputVolumes                                = "input_volumes"
	Attr_InstanceSnapshots                           = "instance_snapshots"
	Attr_InstanceVolumes                             = "instance_volumes"
	Attr_Instances                                   = "instances"
	Attr_IsActive                                    = "is_active"
	Attr_Jumbo                                       = "jumbo"
	Attr_Key                                         = "key"
	Attr_KeyCreationDate                             = "creation_date"
	Attr_KeyID                                       = "key_id"
	Attr_KeyName                                     = "name"
	Attr_Keys                                        = "keys"
	Attr_Language                                    = "language"
	Attr_LastUpdateDate                              = "last_update_date"
	Attr_LastUpdatedDate                             = "last_updated_date"
	Attr_Leases                                      = "leases"
	Attr_LicenseRepositoryCapacity                   = "license_repository_capacity"
	Attr_Location                                    = "location"
	Attr_MTU                                         = "mtu"
	Attr_MacAddress                                  = "macaddress"
	Attr_MasterChangedVolumeName                     = "master_changed_volume_name"
	Attr_MasterVolumeName                            = "master_volume_name"
	Attr_Max                                         = "max"
	Attr_MaxAllocationSize                           = "max_allocation_size"
	Attr_MaxAvailable                                = "max_available"
	Attr_MaxCoresAvailable                           = "max_cores_available"
	Attr_MaxMem                                      = "maxmem"
	Attr_MaxMemoryAvailable                          = "max_memory_available"
	Attr_MaxProc                                     = "maxproc"
	Attr_MaxVirtualCores                             = "max_virtual_cores"
	Attr_MaximumStorageAllocation                    = "max_storage_allocation"
	Attr_Members                                     = "members"
	Attr_Memory                                      = "memory"
	Attr_Message                                     = "message"
	Attr_Metered                                     = "metered"
	Attr_Min                                         = "min"
	Attr_MinMem                                      = "minmem"
	Attr_MinProc                                     = "minproc"
	Attr_MinVirtualCores                             = "min_virtual_cores"
	Attr_MirroringState                              = "mirroring_state"
	Attr_Name                                        = "name"
	Attr_NetworkID                                   = "network_id"
	Attr_NetworkName                                 = "network_name"
	Attr_NetworkPorts                                = "network_ports"
	Attr_Networks                                    = "networks"
	Attr_NumberOfVolumes                             = "number_of_volumes"
	Attr_Onboardings                                 = "onboardings"
	Attr_OperatingSystem                             = "operating_system"
	Attr_PVMInstanceID                               = "pvm_instance_id"
	Attr_PVMInstances                                = "pvm_instances"
	Attr_PVMSnapshots                                = "pvm_snapshots"
	Attr_PercentComplete                             = "percent_complete"
	Attr_PinPolicy                                   = "pin_policy"
	Attr_PlacementGroupID                            = "placement_group_id"
	Attr_PlacementGroups                             = "placement_groups"
	Attr_Policy                                      = "policy"
	Attr_Pool                                        = "pool"
	Attr_PoolName                                    = "pool_name"
	Attr_Port                                        = "port"
	Attr_PortID                                      = "portid"
	Attr_PrimaryRole                                 = "primary_role"
	Attr_ProcType                                    = "proctype"
	Attr_Processors                                  = "processors"
	Attr_ProfileID                                   = "profile_id"
	Attr_Profiles                                    = "profiles"
	Attr_Progress                                    = "progress"
	Attr_PublicIP                                    = "public_ip"
	Attr_Region                                      = "region"
	Attr_RemoteCopyID                                = "remote_copy_id"
	Attr_RemoteCopyRelationshipNames                 = "remote_copy_relationship_names"
	Attr_RemoteCopyRelationships                     = "remote_copy_relationships"
	Attr_ReplicationEnabled                          = "replication_enabled"
	Attr_ReplicationSites                            = "replication_sites"
	Attr_ReplicationStatus                           = "replication_status"
	Attr_ReplicationType                             = "replication_type"
	Attr_ReservedCores                               = "reserved_cores"
	Attr_ResultsOnboardedVolumes                     = "results_onboarded_volumes"
	Attr_ResultsVolumeOnboardingFailures             = "results_volume_onboarding_failures"
	Attr_SPPPlacementGroups                          = "spp_placement_groups"
	Attr_SSHKey                                      = "ssh_key"
	Attr_Shareable                                   = "shreable"
	Attr_SharedCoreRatio                             = "shared_core_ratio"
	Attr_SharedProcessorPool                         = "shared_processor_pool"
	Attr_SharedProcessorPoolID                       = "shared_processor_pool_id"
	Attr_SharedProcessorPoolPlacementGroups          = "spp_placement_groups"
	Attr_SharedProcessorPoolStatus                   = "status"
	Attr_SharedProcessorPools                        = "shared_processor_pools"
	Attr_Size                                        = "size"
	Attr_SourceVolumeName                            = "source_volume_name"
	Attr_Speed                                       = "speed"
	Attr_StartTime                                   = "start_time"
	Attr_State                                       = "state"
	Attr_Status                                      = "status"
	Attr_StatusDescriptionErrors                     = "status_description_errors"
	Attr_StatusDetail                                = "status_detail"
	Attr_StoragePool                                 = "storage_pool"
	Attr_StoragePoolAffinity                         = "storage_pool_affinity"
	Attr_StoragePoolsCapacity                        = "storage_pools_capacity"
	Attr_StorageType                                 = "storage_type"
	Attr_StorageTypesCapacity                        = "storage_types_capacity"
	Attr_Synchronized                                = "synchronized"
	Attr_SysType                                     = "systype"
	Attr_SystemPoolName                              = "system_pool_name"
	Attr_SystemPools                                 = "system_pools"
	Attr_Systems                                     = "systems"
	Attr_TargetVolumeName                            = "target_volume_name"
	Attr_TenantID                                    = "tenant_id"
	Attr_TenantName                                  = "tenant_name"
	Attr_TotalCapacity                               = "total_capacity"
	Attr_TotalInstances                              = "total_instances"
	Attr_TotalMemoryConsumed                         = "total_memory_consumed"
	Attr_TotalProcessorsConsumed                     = "total_processors_consumed"
	Attr_TotalSSDStorageConsumed                     = "total_ssd_storage_consumed"
	Attr_TotalStandardStorageConsumed                = "total_standard_storage_consumed"
	Attr_Type                                        = "type"
	Attr_URL                                         = "url"
	Attr_Uncapped                                    = "uncapped"
	Attr_UsedIPCount                                 = "used_ip_count"
	Attr_UsedIPPercent                               = "used_ip_percent"
	Attr_UserIPAddress                               = "user_ip_address"
	Attr_VCPUs                                       = "vcpus"
	Attr_VLanID                                      = "vlan_id"
	Attr_VPCCRNs                                     = "vpc_crns"
	Attr_VPCEnabled                                  = "vpc_enabled"
	Attr_VirtualCoresAssigned                        = "virtual_cores_assigned"
	Attr_VolumeGroupName                             = "volume_group_name"
	Attr_VolumeGroups                                = "volume_groups"
	Attr_VolumeIDs                                   = "volume_ids"
	Attr_VolumePool                                  = "volume_pool"
	Attr_VolumeSnapshots                             = "volume_snapshots"
	Attr_Volumes                                     = "volumes"
	Attr_WWN                                         = "wwn"
	Attr_Workspaces                                  = "workspaces"
	Attr_SharedProcessorPoolName                     = "name"
	Attr_SharedProcessorPoolHostID                   = "host_id"
	Attr_SharedProcessorPoolReservedCores            = "reserved_cores"
	Attr_SharedProcessorPoolAvailableCores           = "available_cores"
	Attr_SharedProcessorPoolAllocatedCores           = "allocated_cores"
	Attr_SharedProcessorPoolStatusDetail             = "status_detail"
	Attr_SharedProcessorPoolInstances                = "instances"
	Attr_SharedProcessorPoolInstanceCpus             = "cpus"
	Attr_SharedProcessorPoolInstanceUncapped         = "uncapped"
	Attr_SharedProcessorPoolInstanceAvailabilityZone = "availability_zone"
	Attr_SharedProcessorPoolInstanceId               = "id"
	Attr_SharedProcessorPoolInstanceMemory           = "memory"
	Attr_SharedProcessorPoolInstanceName             = "name"
	Attr_SharedProcessorPoolInstanceStatus           = "status"
	Attr_SharedProcessorPoolInstanceVcpus            = "vcpus"
	Arg_PIInstanceSharedProcessorPool                = "pi_shared_processor_pool"
	// TODO: Second Half Cleanup, remove extra variables

	// SAP Profile
	PISAPProfiles         = "profiles"
	PISAPProfileCertified = "certified"
	PISAPProfileCores     = "cores"
	PISAPProfileMemory    = "memory"
	PISAPProfileID        = "profile_id"
	PISAPProfileType      = "type"

	// DHCP
	Arg_DhcpCidr              = "pi_cidr"
	Arg_DhcpID                = "pi_dhcp_id"
	Arg_DhcpCloudConnectionID = "pi_cloud_connection_id"
	Arg_DhcpDnsServer         = "pi_dns_server"
	Arg_DhcpName              = "pi_dhcp_name"
	Arg_DhcpSnatEnabled       = "pi_dhcp_snat_enabled"

	Attr_DhcpServers           = "servers"
	Attr_DhcpID                = "dhcp_id"
	Attr_DhcpLeases            = "leases"
	Attr_DhcpLeaseInstanceIP   = "instance_ip"
	Attr_DhcpLeaseInstanceMac  = "instance_mac"
	Attr_DhcpNetworkDeprecated = "network" // to deprecate
	Attr_DhcpNetworkID         = "network_id"
	Attr_DhcpNetworkName       = "network_name"
	Attr_DhcpStatus            = "status"

	// Instance
	Arg_PVMInstanceId           = "pi_instance_id"
	Arg_PVMInstanceActionType   = "pi_action"
	Arg_PVMInstanceHealthStatus = "pi_health_status"

	PVMInstanceHealthOk      = "OK"
	PVMInstanceHealthWarning = "WARNING"

	//Added timeout values for warning  and active status
	warningTimeOut = 60 * time.Second
	activeTimeOut  = 2 * time.Minute
	// power service instance capabilities
	CUSTOM_VIRTUAL_CORES = "custom-virtualcores"

	//Arg_CloudInstanceID                 = "pi_cloud_instance_id"
	PIInstanceDeploymentType            = "pi_deployment_type"
	PIInstanceMigratable                = "pi_migratable"
	PIInstanceNetwork                   = "pi_network"
	PIInstanceLicenseRepositoryCapacity = "pi_license_repository_capacity"
	PIInstanceStoragePool               = "pi_storage_pool"
	PIInstanceStorageType               = "pi_storage_type"
	PISAPInstanceProfileID              = "pi_sap_profile_id"
	PISAPInstanceDeploymentType         = "pi_sap_deployment_type"
	PIInstanceSharedProcessorPool       = "pi_shared_processor_pool"
	PIInstanceStorageConnection         = "pi_storage_connection"
	PIInstanceStoragePoolAffinity       = "pi_storage_pool_affinity"

	PIInstanceUserData  = "pi_user_data"
	PIInstanceVolumeIds = "pi_volume_ids"

	Attr_PIInstanceSharedProcessorPool   = "shared_processor_pool"
	Attr_PIInstanceSharedProcessorPoolID = "shared_processor_pool_id"

	// Placement Group
	PIPlacementGroupID      = "placement_group_id"
	PIPlacementGroupMembers = "members"

	// Volume
	PIAffinityPolicy        = "pi_affinity_policy"
	PIAffinityVolume        = "pi_affinity_volume"
	PIAffinityInstance      = "pi_affinity_instance"
	PIAntiAffinityInstances = "pi_anti_affinity_instances"
	PIAntiAffinityVolumes   = "pi_anti_affinity_volumes"

	// IBM PI Volume Group
	PIVolumeGroupName                 = "pi_volume_group_name"
	PIVolumeGroupsVolumeIds           = "pi_volume_ids"
	PIVolumeGroupConsistencyGroupName = "pi_consistency_group_name"
	PIVolumeGroupID                   = "pi_volume_group_id"
	PIVolumeGroupAction               = "pi_volume_group_action"
	PIVolumeOnboardingID              = "pi_volume_onboarding_id"

	// Disaster Recovery Location
	PIDRLocation = "location"

	// VPN
	PIVPNConnectionId                         = "connection_id"
	PIVPNConnectionStatus                     = "connection_status"
	PIVPNConnectionDeadPeerDetection          = "dead_peer_detections"
	PIVPNConnectionDeadPeerDetectionAction    = "action"
	PIVPNConnectionDeadPeerDetectionInterval  = "interval"
	PIVPNConnectionDeadPeerDetectionThreshold = "threshold"
	PIVPNConnectionLocalGatewayAddress        = "local_gateway_address"
	PIVPNConnectionVpnGatewayAddress          = "gateway_address"

	// Cloud Connections
	PICloudConnectionTransitEnabled = "pi_cloud_connection_transit_enabled"

	// SPP Placement Group

	Attr_SPPPlacementGroupID      = "spp_placement_group_id"
	Attr_SPPPlacementGroupMembers = "members"
	Attr_SPPPlacementGroupPolicy  = "policy"
	Attr_SPPPlacementGroupName    = "name"

	// status
	// common status states
	StatusShutoff = "SHUTOFF"
	StatusActive  = "ACTIVE"
	StatusResize  = "RESIZE"
	StatusError   = "ERROR"
	StatusBuild   = "BUILD"
	StatusPending = "PENDING"
	SctionStart   = "start"
	SctionStop    = "stop"

	// Workspaces
	Attr_WorkspaceCapabilities = "pi_workspace_capabilities"
	Attr_WorkspaceDetails      = "pi_workspace_details"
	Attr_WorkspaceID           = "pi_workspace_id"
	Attr_WorkspaceLocation     = "pi_workspace_location"
	Attr_WorkspaceName         = "pi_workspace_name"
	Attr_WorkspaceStatus       = "pi_workspace_status"
	Attr_WorkspaceType         = "pi_workspace_type"

	// Datacenter
	Arg_DatacenterZone          = "pi_datacenter_zone"
	Attr_DatacenterCapabilities = "pi_datacenter_capabilities"
	Attr_DatacenterLocation     = "pi_datacenter_location"
	Attr_DatacenterStatus       = "pi_datacenter_status"
	Attr_DatacenterType         = "pi_datacenter_type"
	Attr_DatacenterHref         = "pi_datacenter_href"

	// IBM PI Workspace
	PIWorkspaceName          = "pi_name"
	PIWorkspaceDatacenter    = "pi_datacenter"
	PIWorkspaceResourceGroup = "pi_resource_group_id"
	PIWorkspacePlan          = "pi_plan"
)
